services:
  kha-app:
    image: eclipse-temurin:21-jre
    ports:
      - "8002:8080"
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - SPRING_PROFILES_ACTIVE=sandbox
    command: ["java", "-cp", "libs/*:kha-portal-1.0.0.jar", "com.defi.Main"]
    restart: unless-stopped
    networks:
      - shared_network
networks:
  shared_network:
    external: true