CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS user_has_role (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    PRIMARY KEY(user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx__user_has_role__user_id ON user_has_role(user_id);
CREATE INDEX IF NOT EXISTS idx__user_has_role__role_id ON user_has_role(role_id);

CREATE TABLE group_has_role (
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx__group_has_role__group_id ON group_has_role(group_id);
CREATE INDEX IF NOT EXISTS idx__group_has_role__role_id ON group_has_role(role_id);

