-- =============================================
-- BẢNG SESSIONS
-- =============================================
CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    start_time BIGINT NOT NULL,
    refresh_time BIGINT NOT NULL,
    expired_time BIGINT NOT NULL,
    not_before BIGINT NOT NULL,
    duration BIGINT NOT NULL,
    ip_address VARCHAR(255),
    user_agent TEXT,
    metadata JSONB
);

-- =============================================
-- INDEXES
-- =============================================

-- Primary indexes
CREATE INDEX IF NOT EXISTS idx__sessions__user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx__sessions_ip_address ON sessions(ip_address);
CREATE INDEX IF NOT EXISTS idx__sessions__expired_time ON sessions(expired_time);
-- Composite indexes for common queries
CREATE INDEX IF NOT EXISTS idx__sessions_user_id__expired_time ON sessions(user_id, expired_time);
CREATE INDEX IF NOT EXISTS idx__sessions__expired_time__not_before ON sessions(expired_time, not_before);